Algoritmo "Pares e impares 'enquanto'"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/01/2026
Var
// Seção de Declarações das variáveis 
 par,i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 i<-1
 Enquanto i<=100 faça
 i<-i+1
 Se i%2=0 entao
 Escreval("Impares de 1 a 100=",i-1)
 Escreval("Pare    de 1 a 100=",i)
 Fimse
 Fimenquanto

Fimalgoritmo