Algoritmo "Tabuada 'enquanto'"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/01/2026
Var
// Seção de Declarações das variáveis 
 num,i:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
  i<-1
  Escreval("Digite um numero de (1-9):")
  Leia(num)
  Enquanto i<= 10 faça
  Escreval(num, "x", i, "=", num*i)
  i<-i+1
  Fimenquanto


Fimalgoritmo