Algoritmo "Lista de Nomes"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 27/01/2026
Var
// Seção de Declarações das variáveis 
 i:inteiro
 nome:caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Para i de 1 ate 30 faça
 Escreval("Digite o nome do aluno:")
 Leia(nome)
 fimpara

Fimalgoritmo