Algoritmo "Cadastro Academinco"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/01/2026
Var
// Seção de Declarações das variáveis 

 nome,curso:caracter
Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite seu nome completo:")
 Leia(nome)
 Escreva("Digite seu curso:")
 Leia(curso)
 Escreva("Parabéns " ,nome, " pela aprovação no curso de ",curso)

Fimalgoritmo