Algoritmo "Conversão de Graus"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2026
Var
// Seção de Declarações das variáveis 
  celsius,fahrenheit:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite o número de Celsius: ")
 Leia(celsius)
 fahrenheit<-(celsius*1.8)+32
 Escreva("Realizando a conversão dos ",celsius, " para Fahrenheit e igual: ", fahrenheit)
Fimalgoritmo