Algoritmo "Idade em meses e dias"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2026
Var
// Seção de Declarações das variáveis 
 anos,meses,dias:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite a idade em anos: ")
 Leia(anos)
 meses<-anos*12
 dias<-anos*365
 Escreval("Sua idade em meses e igual:",meses)
 Escreval("Sua idade em dias e aproximadamente:",dias)

Fimalgoritmo