Algoritmo "Impar ou par"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 26/01/2026
Var
// Seção de Declarações das variáveis 
 num:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreval("Digite um número de (0-9): ")
 Leia(num)
 Se num%2=0 então
 Escreval("O numero que você digitou e par")
 Senao
 Escreval("O numero que você digitou e impar")
 Fimse

Fimalgoritmo