Algoritmo "Maioridade 18"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2026
Var
// Seção de Declarações das variáveis 
 idade:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite a sua idade:")
 Leia(idade)
 Se idade>=18 então
 Escreva("Já alcançou a maioridade")
 Senao
 Escreva("Ainda e menor de idade")
 Fimse
Fimalgoritmo