Algoritmo "Operações Matematicas"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 22/01/2026
Var
// Seção de Declarações das variáveis 
 x,y:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite um número de 1-9: ")
 Leia(x)
 Escreva("Digite um segundo número de 1-9: ")
 Leia(y)
 Escreval("A soma desses números e igual:",x+y)
 Escreval("A subtração desses números e igual:",x-y)
 Escreval("A multiplicação desses números e igual:",x*y)
 Escreval("A divisão desses números e igual:",x/y)

Fimalgoritmo