Algoritmo "Área de um retalgulo"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 23/01/2026
Var
// Seção de Declarações das variáveis 
  base,altura,area:inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
 Escreva("Digite a metrica da base do retangulo: ")
 Leia(base)
 Escreva("Digite a metrica da altura do retangulo: ")
 Leia(altura)
 area<-base*altura
 Escreva("A área do retangulo e igual:",area)
Fimalgoritmo